# Generated by Django 5.2.17 on 2026-09-30 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=255)),
                ('foreground_ms', models.BigIntegerField(default=0)),
                ('rx_bytes', models.BigIntegerField(default=0)),
                ('tx_bytes', models.BigIntegerField(default=0)),
                ('mobile_rx_bytes', models.BigIntegerField(default=0)),
                ('mobile_tx_bytes', models.BigIntegerField(default=0)),
                ('wifi_rx_bytes', models.BigIntegerField(default=0)),
                ('wifi_tx_bytes', models.BigIntegerField(default=0)),
                ('gps_overlap_ms', models.BigIntegerField(default=0)),
                ('camera_in_use_ms', models.BigIntegerField(default=0)),
                ('torch_on_ms', models.BigIntegerField(default=0)),
                ('estimated_mah', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['-estimated_mah', 'package_name'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.CharField(max_length=191, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('agent_version', models.CharField(blank=True, max_length=64)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('last_level', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['label', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ActivityUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=512)),
                ('foreground_ms', models.BigIntegerField(default=0)),
                ('estimated_mah', models.FloatField(default=0)),
                ('app_usage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='telemetry.appusage')),
            ],
            options={
                'ordering': ['-estimated_mah', 'class_name'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('timezone_offset_minutes', models.SmallIntegerField(default=0)),
                ('usage_access', models.BooleanField(default=True)),
                ('level_start', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('level_end', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('measured_mah', models.FloatField(default=0)),
                ('charged_mah', models.FloatField(default=0)),
                ('charging_ms', models.BigIntegerField(default=0)),
                ('discharging_ms', models.BigIntegerField(default=0)),
                ('temp_min', models.FloatField(blank=True, null=True)),
                ('temp_max', models.FloatField(blank=True, null=True)),
                ('temp_avg', models.FloatField(blank=True, null=True)),
                ('health', models.CharField(blank=True, max_length=32)),
                ('voltage_mv_avg', models.FloatField(blank=True, null=True)),
                ('cycle_count', models.IntegerField(blank=True, null=True)),
                ('thermal_status_max', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('confidence', models.CharField(blank=True, max_length=32)),
                ('screen_interactive_ms', models.BigIntegerField(default=0)),
                ('screen_aod_ms', models.BigIntegerField(default=0)),
                ('screen_locked_ms', models.BigIntegerField(default=0)),
                ('brightness_min', models.FloatField(blank=True, null=True)),
                ('brightness_max', models.FloatField(blank=True, null=True)),
                ('brightness_avg', models.FloatField(blank=True, null=True)),
                ('short_session_count', models.PositiveIntegerField(default=0)),
                ('screen_sessions', models.JSONField(blank=True, default=list)),
                ('total_mb', models.FloatField(blank=True, null=True)),
                ('avail_mb_min', models.FloatField(blank=True, null=True)),
                ('avail_mb_avg', models.FloatField(blank=True, null=True)),
                ('low_memory_ms', models.BigIntegerField(default=0)),
                ('gps_enabled_ms', models.BigIntegerField(default=0)),
                ('system_mah', models.FloatField(default=0)),
                ('received_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='telemetry.device')),
            ],
            options={
                'ordering': ['period_start'],
            },
        ),
        migrations.AddField(
            model_name='appusage',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='telemetry.report'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(fields=('device', 'period_start'), name='uniq_device_period'),
        ),
    ]
